### ISSUE TITLE
Add external documents for the LLM to search using text embeddings

### ISSUE THREAD

**Issue by syntax-tee** [kekoexchange/personal-llm#17]
## Summary:  
Add feature to existing LLM project, the feature should allow search using text embeddings.

1. Review Product Requirement Document or RFC if available.
2. Model the entity in database.
3. Perform schema update
4. Schema migration with yoyo-migration

## Acceptance Criteria:

- Valid text input with appropriate text length single / multiline search query included
- Ignore case sensitivity, convert text in uppercase to lowercase
- Implement a trie algorithm on the frontend for substring search or text matching or other text search algorithm
- Ensure unit tests for the features while considering edge cases
- Write automated test suites

**Comment by kayashaolu** [comment]
Hey! So I would highly recommend checking out this article on [embedding models](https://ollama.com/blog/embedding-models). 

Ask well as this video on how to build a [RAG using just Python and Ollama ](https://www.youtube.com/watch?v=GxLoMquHynY).

By using a vector database instead of a typical database, we can use an embeddings model to convert the text we want to search and put it in the database, and then add the data to every prompt sent to our personal LLM.

Here's the code to the video: https://github.com/kekoexchange/personal-llm/issues/17

**Comment by syntax-tee** [comment]
Will check the resources shared.
